---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
SSViewer:
  theme: 'simple'
Member:
  extensions:
   - GFSGMemberExtension
Group:
  extensions:
   - GFSGGroupExtension
Email:
  admin_email: ben@benbillbob.com
SiteConfig:
  extensions:
   - MySiteConfig
SSViewer:
  source_file_comments: false
Only:
  environment: 'dev'
FormSpamProtectionExtension:
  default_spam_protector: NocaptchaProtector
NocaptchaField:
  site_key: "6Lc7wzAUAAAAAPf24Z1YPrVnVsHs5r5seE1ZhYzc" #Your site key (required)
  secret_key: "6Lc7wzAUAAAAAPM_icJUJvLBH-uBNQitza9Ld0c4" #Your secret key (required)
  verify_ssl: true #Allows you to disable php-curl's SSL peer verification by setting this to false (optional, defaults to true)
  default_theme: "light" #Default theme color (optional, light or dark, defaults to light)
  default_type: "image" #Default captcha type (optional, image or audio, defaults to image)
  default_size: "normal" #Default size (optional, normal, compact or invisible, defaults to normal)
  default_badge: "bottomright" #Default badge position (bottomright, bottomleft or inline, defaults to bottomright)
  proxy_server: "" #Your proxy server address (optional)
  proxy_auth: "" #Your proxy server authentication information (optional)