---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
SSViewer:
  theme: 'simple'
Member:
  extensions:
   - GFSGMemberExtension
Group:
  extensions:
   - GFSGGroupExtension
Email:
  admin_email: ben@benbillbob.com
SiteConfig:
  extensions:
   - MySiteConfig
SSViewer:
  source_file_comments: true
Only:
  environment: 'dev'